const TALENT_DATA = {
  level: [
    {
      level: 1,
      mora: 0,
      greenTalent: 0,
      blueTalent: 0,
      purpleTalent: 0,
      commonMaterialWhite: 0,
      commonMaterialGreen: 0,
      commonMaterialBlue: 0,
      bossMaterial: 0,
      crown: 0,
    },
    {
      level: 2,
      mora: 12500,
      greenTalent: 3,
      blueTalent: 0,
      purpleTalent: 0,
      commonMaterialWhite: 6,
      commonMaterialGreen: 0,
      commonMaterialBlue: 0,
      bossMaterial: 0,
      crown: 0,
    },
    {
      level: 3,
      mora: 17500,
      greenTalent: 0,
      blueTalent: 2,
      purpleTalent: 0,
      commonMaterialWhite: 0,
      commonMaterialGreen: 3,
      commonMaterialBlue: 0,
      bossMaterial: 0,
      crown: 0,
    },
    {
      level: 4,
      mora: 25000,
      greenTalent: 0,
      blueTalent: 4,
      purpleTalent: 0,
      commonMaterialWhite: 0,
      commonMaterialGreen: 4,
      commonMaterialBlue: 0,
      bossMaterial: 0,
      crown: 0,
    },
    {
      level: 5,
      mora: 30000,
      greenTalent: 0,
      blueTalent: 6,
      purpleTalent: 0,
      commonMaterialWhite: 0,
      commonMaterialGreen: 6,
      commonMaterialBlue: 0,
      bossMaterial: 0,
      crown: 0,
    },
    {
      level: 6,
      mora: 37500,
      greenTalent: 0,
      blueTalent: 9,
      purpleTalent: 0,
      commonMaterialWhite: 0,
      commonMaterialGreen: 9,
      commonMaterialBlue: 0,
      bossMaterial: 0,
      crown: 0,
    },
    {
      level: 7,
      mora: 120000,
      greenTalent: 0,
      blueTalent: 0,
      purpleTalent: 4,
      commonMaterialWhite: 0,
      commonMaterialGreen: 0,
      commonMaterialBlue: 4,
      bossMaterial: 1,
      crown: 0,
    },
    {
      level: 8,
      mora: 260000,
      greenTalent: 0,
      blueTalent: 0,
      purpleTalent: 6,
      commonMaterialWhite: 0,
      commonMaterialGreen: 0,
      commonMaterialBlue: 6,
      bossMaterial: 1,
      crown: 0,
    },
    {
      level: 9,
      mora: 450000,
      greenTalent: 0,
      blueTalent: 0,
      purpleTalent: 12,
      commonMaterialWhite: 0,
      commonMaterialGreen: 0,
      commonMaterialBlue: 9,
      bossMaterial: 2,
      crown: 0,
    },
    {
      level: 10,
      mora: 0,
      greenTalent: 0,
      blueTalent: 0,
      purpleTalent: 16,
      commonMaterialWhite: 0,
      commonMaterialGreen: 0,
      commonMaterialBlue: 12,
      bossMaterial: 2,
      crown: 1,
    },
  ],
};

export default TALENT_DATA;
