const CHARACTER_DATA = {
  heroWit: {
    purple: 20000,
    blue: 5000,
    green: 1000,
  },

  level: [
    { lv: 0, purple: 0, blue: 0, green: 0, mora: 0, exp: 0 },
    { lv: 20, purple: 6, blue: 0, green: 1, mora: 24200, exp: 120175 },
    { lv: 40, purple: 28, blue: 3, green: 4, mora: 115800, exp: 578325 },
    { lv: 50, purple: 29, blue: 0, green: 0, mora: 116000, exp: 579100 },
    { lv: 60, purple: 42, blue: 3, green: 0, mora: 171000, exp: 854125 },
    { lv: 70, purple: 59, blue: 3, green: 1, mora: 239200, exp: 1195925 },
    { lv: 80, purple: 80, blue: 2, green: 2, mora: 322400, exp: 1611875 },
    { lv: 90, purple: 171, blue: 0, green: 4, mora: 684800, exp: 3423125 },
  ],
  ascension: [
    {
      ascension: 0,
      localSpecialty: 0,
      gemGreen: 0,
      gemBlue: 0,
      gemPurple: 0,
      gemOrange: 0,
      commonMaterialWhite: 0,
      commonMaterialGreen: 0,
      commonMaterialBlue: 0,
      bossMaterial: 0,
      mora: 0,
    },
    {
      ascension: 1,
      localSpecialty: 3,
      gemGreen: 1,
      gemBlue: 0,
      gemPurple: 0,
      gemOrange: 0,
      commonMaterialWhite: 3,
      commonMaterialGreen: 0,
      commonMaterialBlue: 0,
      bossMaterial: 0,
      mora: 20000,
    },
    {
      ascension: 2,
      localSpecialty: 10,
      gemGreen: 0,
      gemBlue: 3,
      gemPurple: 0,
      gemOrange: 0,
      commonMaterialWhite: 15,
      commonMaterialGreen: 0,
      commonMaterialBlue: 0,
      bossMaterial: 2,
      mora: 40000,
    },
    {
      ascension: 3,
      localSpecialty: 20,
      gemGreen: 0,
      gemBlue: 6,
      gemPurple: 0,
      gemOrange: 0,
      commonMaterialWhite: 0,
      commonMaterialGreen: 12,
      commonMaterialBlue: 0,
      bossMaterial: 4,
      mora: 60000,
    },
    {
      ascension: 4,
      localSpecialty: 30,
      gemGreen: 0,
      gemBlue: 0,
      gemPurple: 3,
      gemOrange: 0,
      commonMaterialWhite: 0,
      commonMaterialGreen: 18,
      commonMaterialBlue: 0,
      bossMaterial: 8,
      mora: 80000,
    },
    {
      ascension: 5,
      localSpecialty: 45,
      gemGreen: 0,
      gemBlue: 0,
      gemPurple: 6,
      gemOrange: 0,
      commonMaterialWhite: 0,
      commonMaterialGreen: 0,
      commonMaterialBlue: 12,
      bossMaterial: 12,
      mora: 100000,
    },
    {
      ascension: 6,
      localSpecialty: 60,
      gemGreen: 0,
      gemBlue: 0,
      gemPurple: 0,
      gemOrange: 6,
      commonMaterialWhite: 0,
      commonMaterialGreen: 0,
      commonMaterialBlue: 24,
      bossMaterial: 20,
      mora: 120000,
    },
  ],
};
export default CHARACTER_DATA;
