export const CharacterActionTypes = {
  HANDLE_CHANGE: "HANDLE_CHANGE",
  HANDLE_SUBMIT: "HANDLE_SUBMIT",
  HANDLE_RADIO_BUTTON: "HANDLE_RADIO_BUTTON",
  HANDLE_CURRENT_LEVEL: "HANDLE_CURRENT_LEVEL",
  HANDLE_DESIRED_LEVEL: "HANDLE_DESIRED_LEVEL",
  FETCH_CHARACTERS_START: "FETCH_CHARACTERS_START",
  FETCH_CHARACTERS_SUCCESS: "FETCH_CHARACTERS_SUCCESS",
  FETCH_CHARACTERS_FAILURE: "FETCH_CHARACTERS_FAILURE",
  FETCH_CHARACTER_PORTRAITS_START: "FETCH_CHARACTERSPORTRAIT_START",
  FETCH_CHARACTER_PORTRAITS_SUCCESS: "FETCH_CHARACTER_PORTRAITS_SUCCESS",
  FETCH_CHARACTER_PORTRAITS_FAILURE: "FETCH_CHARACTERS_PORTRAITSFAILURE",
};
