export const CharacterActionTypes = {
  HANDLE_CHANGE: "HANDLE_CHANGE",
  HANDLE_SUBMIT: "HANDLE_SUBMIT",
  HANDLE_RADIO_BUTTON: "HANDLE_RADIO_BUTTON",
  HANDLE_CURRENT_LEVEL: "HANDLE_CURRENT_LEVEL",
  HANDLE_DESIRED_LEVEL: "HANDLE_DESIRED_LEVEL",
};
